apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-backend
  template:
    metadata:
      labels:
        app: marketplace-backend
    spec:
      containers:
      - name: marketplace-backend
        image: hub.docker.com/repository/docker/salileoss/marketplace-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: marketplace-backend
#   labels:
#     app: marketplace-backend
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 8080
#     targetPort: 8080
#   selector:
#     app:marketplace-backend

