apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-backend
spec:
  selector:
    matchLabels:
      app: marketplace-backend
  template:
    metadata:
      labels:
        app: marketplace-backend
    spec:
      containers:
      - name: marketplace-backend
        image: salileoss/marketplace-backend
        ports:
        - containerPort: 8080
